name: todos_data_source
description: A generic interface for managing todos.
version: 0.1.0+1


environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  equatable: ^2.0.5
  json_annotation: ^4.6.0
  meta: ^1.7.0

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
